Add test debug build

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -10,9 +10,6 @@ jobs:
       - checkout
       - restore_cache:
           key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
-      #      - run:
-      #         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
-      #         command: sudo chmod +x ./gradlew
       - run:
           name: Download Dependencies
           command: |
@@ -24,9 +21,9 @@ jobs:
           key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
 
       # Generate apk
-      - run: ./gradlew assembleDebug
+      - run: ./gradlew assembleDebug assembleAndroidTest
 
-      # Upload app to BrowserStack and set app url in an environment variable.
+      # Upload apk to BrowserStack and set app url in an environment variable.
       - run:
           name : App upload and Set app id in environment variable.
           command : |
@@ -43,5 +40,24 @@ jobs:
               echo "App upload failed, reason : ",$UPLOAD_ERROR_MESSAGE
               exit 1;
             fi
+
+      # Upload tests apk to BrowserStack and set app url in an environment variable.
+      - run:
+          name: App upload and Set app id in environment variable.
+          command: |
+            APP_UPLOAD_RESPONSE=$(curl -u "vgsvendors1:xjSscpXkZ8pUHxxz6Nsd" -X POST "https://api-cloud.browserstack.com/app-automate/espresso/test-suite" -F "file=@app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk")
+            echo "APP_UPLOAD_RESPONSE :  " + $APP_UPLOAD_RESPONSE
+            APP_TESTS_ID=$(echo $APP_UPLOAD_RESPONSE | jq -r ".app_url")
+            if [ APP_TESTS_ID != null ]; then
+              echo "Apk uploaded to BrowserStack with app id : ",APP_TESTS_ID;
+              echo "export BROWSERSTACK_APP_TEST_ID=APP_TESTS_ID" >> $BASH_ENV;
+              source $BASH_ENV;
+              echo "Setting value of BROWSERSTACK_APP_TEST_ID in environment variables to  ",APP_TESTS_ID;
+            else
+              UPLOAD_ERROR_MESSAGE=$(echo $APP_UPLOAD_RESPONSE | jq -r ".error")
+              echo "App upload failed, reason : ",$UPLOAD_ERROR_MESSAGE
+              exit 1;
+            fi
+
       # run tests!
       - run: ./gradlew test
