test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -61,7 +61,19 @@ aliases:
     - *attach_workspace
     - run:
         name: Upload build
-        command: echo "Apk uploaded to BrowserStack with app id"
+        command: |
+          APP_UPLOAD_RESPONSE=$(curl -u "dmytrodmytryshyn1:DyKfpdxjcn5Fh9B324VB" -X POST https://api-cloud.browserstack.com/app-automate/upload -F "file=@app/build/outputs/apk/debug/app-debug.apk")
+          APP_ID=$(echo $APP_UPLOAD_RESPONSE | jq -r ".app_url")
+          if [ $APP_ID != null ]; then
+            echo "Apk uploaded to BrowserStack with app id : ",$APP_ID;
+            echo "export BROWSERSTACK_APP_ID=$APP_ID" >> $BASH_ENV;
+            source $BASH_ENV;
+            echo "Setting value of BROWSERSTACK_APP_ID in environment variables to  ",$APP_ID;
+          else
+            UPLOAD_ERROR_MESSAGE=$(echo $APP_UPLOAD_RESPONSE | jq -r ".error")
+            echo "App upload failed, reason : ",$UPLOAD_ERROR_MESSAGE
+            exit 1;
+          fi
 
   # dependency groups
   - &prepare_sources
